import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Barlow } from 'next/font/google';
import './globals.css';

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '900'],
  variable: '--font-barlow',
});


const fightClub = localFont({
  src: '../public/assets/fonts/FIGHTT3_.ttf', 
  variable: '--font-fightclub',
});

const grandmaster = localFont({
  src: '../public/assets/fonts/Grandmaster-Regular.otf',
  variable: '--font-grandmaster',
});

const DDIN = localFont({
  src: '../public/assets/fonts/D-DIN.otf',
  variable: '--font-DD',
});

const Halfdeath = localFont({
  src: '../public/assets/fonts/HALF\ DEATH.ttf',
  variable: '--font-halfdeath',
});

const latosce = localFont({
  src: '../public/assets/fonts/latosce.ttf',
  variable: '--font-lacto',
});

const Odachi = localFont({
  src: '../public/assets/fonts/Odachi.otf',
  variable: '--font-Odachi',
});


const ttTrailers = localFont({
  src: '../public/assets/fonts/TT Trailers Trial Bold.ttf',
  variable: '--font-tt',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} ${Odachi.variable} ${latosce.variable} ${Halfdeath.variable} ${DDIN.variable} ${fightClub.variable} ${grandmaster.variable} ${ttTrailers.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
